config/routes.rb
Rails.application.routes.draw do
  get 'admin', to: 'admin#index'
  post 'admin/send', to: 'admin#send_messages'

  get  '/messages/new'
  post '/messages', to: 'message#create', as: 'message_create'
  get  '/messages/confirm/:token', to: 'message#confirm', as: 'message_confirm'
  root 'message#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  has_secure_token :auth_token
  validates :content, presence: true
  validates :email_address, presence: true
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :authenticate

  def authenticate
    authenticate_or_request_with_http_basic('Administration') do |username, password|
      username == 'admin' && password == ENV["ADMIN_PASSWORD"]
    end
  end

  def index
    messages = Message.all

    total_words = messages.reduce(0) { |sum, message| sum + message.content.split.count }.to_f
    if messages.length > 0
      @average_message_length = total_words / messages.length
    else
      @average_message_length = 0
    end

    @messages_logged = messages.count
    @messages_authorized = messages.find_all { |message| message.authorized }.count
    @messages_sent = messages.find_all { |message| message.sent }.count

    @distinct_zips = Message.select(:zip).distinct.length
  end

  def send_messages
    unsent_messages = Message.where({sent: false, authorized: true})

    unsent_messages.each do |message|
      UserMailer.send_message_from_2016(message).deliver_later
      message.sent = true;
      message.save
    end

    @messages_sent = unsent_messages.length
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/message_controller.rb
class MessageController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)

    if @message.save
      UserMailer.confirm(@message).deliver_later
      flash[:notice] = "Your message has been saved"
      redirect_to root_path
    else
      @errors = @message.errors.full_messages
      render 'new'
    end
  end


  def confirm
    @message = Message.find_by(auth_token: params[:token])
    if @message
      @message.authorized = true
      @message.save
      flash[:notice] = "Your email address (#{@message.email_address}) has been confirmed."
      redirect_to root_path
    else
      flash[:error] = "Unable to confirm your email address. Please contact support@#{Rails.application.config.production_host}"
      logger.error("Bad authorization token received: #{params[:token]}")
      redirect_to root_path
    end
  end

  private

  def message_params
    params.require(:message).permit(:email_address, :content, :zip)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
  def format_floats(number)
    number.round(2)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/message_helper.rb
module MessageHelper
    def days_to_election
        (Date.new(2018,11,6) - Date.today).to_i
    end
end

app/views/admin/index.html.erb
<h1>Message from 2016 Admin</h1>
<p>Messages logged: <%= @messages_logged %></p>
<p>Messages authorized: <%= @messages_authorized %></p>
<p>Messages sent: <%= @messages_sent %></p>
<p>Average message length: <%= format_floats(@average_message_length) %> words</p>
<p>Distinct zip code: <%= @distinct_zips %></p>

<%= form_tag("/admin/send", method: "post") do %>
    <%= submit_tag("Send messages") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Message From 2016</title>

    <link rel="apple-touch-icon" sizes="180x180" href="<%= image_url("apple-touch-icon.png") %>">
    <link rel="icon" type="image/png" href="<%= image_url("favicon-32x32.png") %>" sizes="32x32">
    <link rel="icon" type="image/png" href="<%= image_url("favicon-16x16.png") %>" sizes="16x16">
    <link rel="mask-icon" href="<%= image_url("safari-pinned-tab.svg") %>" color="#5bbad5">
    <meta name="theme-color" content="#ffffff">

    <!-- Facebook -->
    <meta property="og:url"                content="<%= root_url %>"/>
    <meta property="og:type"               content="website" />
    <meta property="og:title"              content="Message From 2016" />
    <meta property="og:description"        content="Write down your hopes, fears, and feelings about this election and we'll send them back to you two months before the midterms. Hold your future self accountable." />
    <meta property="og:image"              content="<%= image_url("message-in-a-bottle.fb.png") %>" />
    <meta property="og:image:height"              content="1200" />
    <meta property="og:image:width"              content="630" />

    <!-- Twitter -->
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="@messagefrom2016" />
    <meta name="twitter:title" content="Message From 2016" />
    <meta name="twitter:description" content="Write down your hopes, fears, and feelings about this election and we'll send them back to you two months before the midterms." />
    <meta name="twitter:image" content="<%= image_url("message-in-a-bottle.twitter.png") %>"/>

    <meta name="viewport" content="width=device-width">
    <meta name="viewport" content="initial-scale=1.0">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
  </head>

  <body>
    <div id="content-wrapper">
      <div class="center">
        <%= image_tag("message-in-a-bottle.svg", {class: "logo"}) %>
      </div>
      <%= yield %>
    </div>
  </body>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-87468145-1', 'auto');
    ga('send', 'pageview');

  </script>
</html>

app/views/message/_social.html.erb
<p class="sharing">
  Get the word out:
</p>

<div class="social">
  <iframe src="https://www.facebook.com/plugins/share_button.php?href=http%3A%2F%2Fwww.messagefrom2016.com&layout=button&size=large&mobile_iframe=true&width=84&height=28&appId"
    width="84"
    height="28"
    style="border:none;overflow:hidden"
    scrolling="no"
    frameborder="0"
    allowTransparency="true">
  </iframe>

  <iframe
    src="https://platform.twitter.com/widgets/tweet_button.html?size=l&text=Write%20a%20letter%20to%20yourself%20about%20the%20election%2C%20%40messagefrom2016%20will%20mail%20it%20back%20to%20you%20before%20midterm%20elections."
    width="77"
    height="28"
    title="Twitter Tweet Button"
    style="border: 0; overflow: hidden;">
  </iframe>
</div>

app/views/message/confirm.html.erb
Your email, <%= @message.email_address %>, has been confirmed.

app/views/message/new.html.erb
<% if flash[:error] %>
  <div class="error"><%= flash[:error] %></div>
<% end %>

<% if flash[:notice] %>
  <div class="notification"><%= flash[:notice] %></div>
  <h2 class="center">
    The midterm elections<br>
    are in <%= days_to_election %> days.
  </h2>

  <%= render partial: "social.html.erb" %>
<% else %>
  <div class="intro">
    <h1>Message from 2016</h1>

    <p>The election of Donald Trump on November 8th, 2016
    set off a tidal wave of sadness, rage, solidarity, and
    action. But, for better and worse, the human brain is
    great at adapting to terrible situations over time.<p>

    <p>Write
    down how you’re feeling right now, and we’ll email it to
    your future self in time for you to do something about
    the midterms.</p>

    <p>Your message and your information will never be shared with anyone but you.</p>
  </div>

  <% if @errors %>
    <ul id="error-list">
      <% @errors.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  <% end %>

  <%= form_for :message, url: message_create_path do |f| %>
    <h1>How are you feeling?</h1>
    <p>What are your hopes? What are your fears? What are you willing to do to make sure this never happens again?</p>
    <p>
      <%= f.text_area :content, required: true %>
    </p>
    <p>
      <%= f.email_field :email_address, placeholder: "email", required: true %>
    </p>

    <p>
      <%= f.text_field :zip, placeholder: "zip (optional)" %>
    </p>

    <p class="center">
      <%= f.submit "save", class: "button" %>
    </p>
  <% end %>
  <div class="center bottom-logo">
    <%= image_tag("message-in-a-bottle.svg", {class: "logo"}) %>
  </div>
<% end %>